# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Mon Jan 26 18:19:46 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(593, 640)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 591, 601))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButton_6_0 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6_0.setText(_fromUtf8(""))
        self.radioButton_6_0.setAutoExclusive(False)
        self.radioButton_6_0.setObjectName(_fromUtf8("radioButton_6_0"))
        self.gridLayout_2.addWidget(self.radioButton_6_0, 6, 0, 1, 1)
        self.radioButton_3_0 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3_0.setText(_fromUtf8(""))
        self.radioButton_3_0.setAutoExclusive(False)
        self.radioButton_3_0.setObjectName(_fromUtf8("radioButton_3_0"))
        self.gridLayout_2.addWidget(self.radioButton_3_0, 3, 0, 1, 1)
        self.radioButton_7_0 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_7_0.setText(_fromUtf8(""))
        self.radioButton_7_0.setAutoExclusive(False)
        self.radioButton_7_0.setObjectName(_fromUtf8("radioButton_7_0"))
        self.gridLayout_2.addWidget(self.radioButton_7_0, 7, 0, 1, 1)
        self.radioButton_0_0 = QtGui.QRadioButton(self.gridLayoutWidget)
        palette = QtGui.QPalette()
        self.radioButton_0_0.setPalette(palette)
        self.radioButton_0_0.setAutoFillBackground(True)
        self.radioButton_0_0.setStyleSheet(_fromUtf8("\n"
""))
        self.radioButton_0_0.setText(_fromUtf8(""))
        self.radioButton_0_0.setCheckable(True)
        self.radioButton_0_0.setAutoExclusive(False)
        self.radioButton_0_0.setObjectName(_fromUtf8("radioButton_0_0"))
        self.gridLayout_2.addWidget(self.radioButton_0_0, 0, 0, 1, 1)
        self.radioButton_2_0 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2_0.setText(_fromUtf8(""))
        self.radioButton_2_0.setAutoExclusive(False)
        self.radioButton_2_0.setObjectName(_fromUtf8("radioButton_2_0"))
        self.gridLayout_2.addWidget(self.radioButton_2_0, 2, 0, 1, 1)
        self.radioButton_1_0 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_1_0.setText(_fromUtf8(""))
        self.radioButton_1_0.setAutoExclusive(False)
        self.radioButton_1_0.setObjectName(_fromUtf8("radioButton_1_0"))
        self.gridLayout_2.addWidget(self.radioButton_1_0, 1, 0, 1, 1)
        self.radioButton_4_0 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4_0.setText(_fromUtf8(""))
        self.radioButton_4_0.setAutoExclusive(False)
        self.radioButton_4_0.setObjectName(_fromUtf8("radioButton_4_0"))
        self.gridLayout_2.addWidget(self.radioButton_4_0, 4, 0, 1, 1)
        self.radioButton_5_0 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5_0.setText(_fromUtf8(""))
        self.radioButton_5_0.setAutoExclusive(False)
        self.radioButton_5_0.setObjectName(_fromUtf8("radioButton_5_0"))
        self.gridLayout_2.addWidget(self.radioButton_5_0, 5, 0, 1, 1)
        self.radioButton_3_1 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3_1.setText(_fromUtf8(""))
        self.radioButton_3_1.setAutoExclusive(False)
        self.radioButton_3_1.setObjectName(_fromUtf8("radioButton_3_1"))
        self.gridLayout_2.addWidget(self.radioButton_3_1, 3, 1, 1, 1)
        self.radioButton_1_6 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_1_6.setText(_fromUtf8(""))
        self.radioButton_1_6.setAutoExclusive(False)
        self.radioButton_1_6.setObjectName(_fromUtf8("radioButton_1_6"))
        self.gridLayout_2.addWidget(self.radioButton_1_6, 1, 6, 1, 1)
        self.radioButton_1_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_1_2.setText(_fromUtf8(""))
        self.radioButton_1_2.setAutoExclusive(False)
        self.radioButton_1_2.setObjectName(_fromUtf8("radioButton_1_2"))
        self.gridLayout_2.addWidget(self.radioButton_1_2, 1, 2, 1, 1)
        self.radioButton_0_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_0_2.setText(_fromUtf8(""))
        self.radioButton_0_2.setAutoExclusive(False)
        self.radioButton_0_2.setObjectName(_fromUtf8("radioButton_0_2"))
        self.gridLayout_2.addWidget(self.radioButton_0_2, 0, 2, 1, 1)
        self.radioButton_0_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_0_4.setText(_fromUtf8(""))
        self.radioButton_0_4.setAutoExclusive(False)
        self.radioButton_0_4.setObjectName(_fromUtf8("radioButton_0_4"))
        self.gridLayout_2.addWidget(self.radioButton_0_4, 0, 4, 1, 1)
        self.radioButton_6_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6_3.setText(_fromUtf8(""))
        self.radioButton_6_3.setAutoExclusive(False)
        self.radioButton_6_3.setObjectName(_fromUtf8("radioButton_6_3"))
        self.gridLayout_2.addWidget(self.radioButton_6_3, 6, 3, 1, 1)
        self.radioButton_2_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2_5.setText(_fromUtf8(""))
        self.radioButton_2_5.setAutoExclusive(False)
        self.radioButton_2_5.setObjectName(_fromUtf8("radioButton_2_5"))
        self.gridLayout_2.addWidget(self.radioButton_2_5, 2, 5, 1, 1)
        self.radioButton_5_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5_4.setText(_fromUtf8(""))
        self.radioButton_5_4.setAutoExclusive(False)
        self.radioButton_5_4.setObjectName(_fromUtf8("radioButton_5_4"))
        self.gridLayout_2.addWidget(self.radioButton_5_4, 5, 4, 1, 1)
        self.radioButton_6_6 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6_6.setText(_fromUtf8(""))
        self.radioButton_6_6.setAutoExclusive(False)
        self.radioButton_6_6.setObjectName(_fromUtf8("radioButton_6_6"))
        self.gridLayout_2.addWidget(self.radioButton_6_6, 6, 6, 1, 1)
        self.radioButton_1_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_1_5.setText(_fromUtf8(""))
        self.radioButton_1_5.setAutoExclusive(False)
        self.radioButton_1_5.setObjectName(_fromUtf8("radioButton_1_5"))
        self.gridLayout_2.addWidget(self.radioButton_1_5, 1, 5, 1, 1)
        self.radioButton_4_1 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4_1.setText(_fromUtf8(""))
        self.radioButton_4_1.setAutoExclusive(False)
        self.radioButton_4_1.setObjectName(_fromUtf8("radioButton_4_1"))
        self.gridLayout_2.addWidget(self.radioButton_4_1, 4, 1, 1, 1)
        self.radioButton_2_1 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2_1.setText(_fromUtf8(""))
        self.radioButton_2_1.setAutoExclusive(False)
        self.radioButton_2_1.setObjectName(_fromUtf8("radioButton_2_1"))
        self.gridLayout_2.addWidget(self.radioButton_2_1, 2, 1, 1, 1)
        self.radioButton_2_7 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2_7.setText(_fromUtf8(""))
        self.radioButton_2_7.setAutoExclusive(False)
        self.radioButton_2_7.setObjectName(_fromUtf8("radioButton_2_7"))
        self.gridLayout_2.addWidget(self.radioButton_2_7, 2, 7, 1, 1)
        self.radioButton_1_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_1_3.setText(_fromUtf8(""))
        self.radioButton_1_3.setAutoExclusive(False)
        self.radioButton_1_3.setObjectName(_fromUtf8("radioButton_1_3"))
        self.gridLayout_2.addWidget(self.radioButton_1_3, 1, 3, 1, 1)
        self.radioButton_4_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4_2.setText(_fromUtf8(""))
        self.radioButton_4_2.setAutoExclusive(False)
        self.radioButton_4_2.setObjectName(_fromUtf8("radioButton_4_2"))
        self.gridLayout_2.addWidget(self.radioButton_4_2, 4, 2, 1, 1)
        self.radioButton_5_7 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5_7.setText(_fromUtf8(""))
        self.radioButton_5_7.setAutoExclusive(False)
        self.radioButton_5_7.setObjectName(_fromUtf8("radioButton_5_7"))
        self.gridLayout_2.addWidget(self.radioButton_5_7, 5, 7, 1, 1)
        self.radioButton_0_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_0_5.setText(_fromUtf8(""))
        self.radioButton_0_5.setAutoExclusive(False)
        self.radioButton_0_5.setObjectName(_fromUtf8("radioButton_0_5"))
        self.gridLayout_2.addWidget(self.radioButton_0_5, 0, 5, 1, 1)
        self.radioButton_0_7 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_0_7.setText(_fromUtf8(""))
        self.radioButton_0_7.setAutoExclusive(False)
        self.radioButton_0_7.setObjectName(_fromUtf8("radioButton_0_7"))
        self.gridLayout_2.addWidget(self.radioButton_0_7, 0, 7, 1, 1)
        self.radioButton_0_6 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_0_6.setText(_fromUtf8(""))
        self.radioButton_0_6.setAutoExclusive(False)
        self.radioButton_0_6.setObjectName(_fromUtf8("radioButton_0_6"))
        self.gridLayout_2.addWidget(self.radioButton_0_6, 0, 6, 1, 1)
        self.radioButton_0_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_0_3.setText(_fromUtf8(""))
        self.radioButton_0_3.setAutoExclusive(False)
        self.radioButton_0_3.setObjectName(_fromUtf8("radioButton_0_3"))
        self.gridLayout_2.addWidget(self.radioButton_0_3, 0, 3, 1, 1)
        self.radioButton_2_6 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2_6.setText(_fromUtf8(""))
        self.radioButton_2_6.setAutoExclusive(False)
        self.radioButton_2_6.setObjectName(_fromUtf8("radioButton_2_6"))
        self.gridLayout_2.addWidget(self.radioButton_2_6, 2, 6, 1, 1)
        self.radioButton_1_7 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_1_7.setText(_fromUtf8(""))
        self.radioButton_1_7.setAutoExclusive(False)
        self.radioButton_1_7.setObjectName(_fromUtf8("radioButton_1_7"))
        self.gridLayout_2.addWidget(self.radioButton_1_7, 1, 7, 1, 1)
        self.radioButton_1_1 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_1_1.setText(_fromUtf8(""))
        self.radioButton_1_1.setAutoExclusive(False)
        self.radioButton_1_1.setObjectName(_fromUtf8("radioButton_1_1"))
        self.gridLayout_2.addWidget(self.radioButton_1_1, 1, 1, 1, 1)
        self.radioButton_1_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_1_4.setText(_fromUtf8(""))
        self.radioButton_1_4.setAutoExclusive(False)
        self.radioButton_1_4.setObjectName(_fromUtf8("radioButton_1_4"))
        self.gridLayout_2.addWidget(self.radioButton_1_4, 1, 4, 1, 1)
        self.radioButton_2_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2_3.setText(_fromUtf8(""))
        self.radioButton_2_3.setAutoExclusive(False)
        self.radioButton_2_3.setObjectName(_fromUtf8("radioButton_2_3"))
        self.gridLayout_2.addWidget(self.radioButton_2_3, 2, 3, 1, 1)
        self.radioButton_4_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4_5.setText(_fromUtf8(""))
        self.radioButton_4_5.setAutoExclusive(False)
        self.radioButton_4_5.setObjectName(_fromUtf8("radioButton_4_5"))
        self.gridLayout_2.addWidget(self.radioButton_4_5, 4, 5, 1, 1)
        self.radioButton_2_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2_4.setText(_fromUtf8(""))
        self.radioButton_2_4.setAutoExclusive(False)
        self.radioButton_2_4.setObjectName(_fromUtf8("radioButton_2_4"))
        self.gridLayout_2.addWidget(self.radioButton_2_4, 2, 4, 1, 1)
        self.radioButton_2_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2_2.setText(_fromUtf8(""))
        self.radioButton_2_2.setAutoExclusive(False)
        self.radioButton_2_2.setObjectName(_fromUtf8("radioButton_2_2"))
        self.gridLayout_2.addWidget(self.radioButton_2_2, 2, 2, 1, 1)
        self.radioButton_3_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3_2.setText(_fromUtf8(""))
        self.radioButton_3_2.setAutoExclusive(False)
        self.radioButton_3_2.setObjectName(_fromUtf8("radioButton_3_2"))
        self.gridLayout_2.addWidget(self.radioButton_3_2, 3, 2, 1, 1)
        self.radioButton_6_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6_5.setText(_fromUtf8(""))
        self.radioButton_6_5.setAutoExclusive(False)
        self.radioButton_6_5.setObjectName(_fromUtf8("radioButton_6_5"))
        self.gridLayout_2.addWidget(self.radioButton_6_5, 6, 5, 1, 1)
        self.radioButton_3_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3_3.setText(_fromUtf8(""))
        self.radioButton_3_3.setAutoExclusive(False)
        self.radioButton_3_3.setObjectName(_fromUtf8("radioButton_3_3"))
        self.gridLayout_2.addWidget(self.radioButton_3_3, 3, 3, 1, 1)
        self.radioButton_5_6 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5_6.setText(_fromUtf8(""))
        self.radioButton_5_6.setAutoExclusive(False)
        self.radioButton_5_6.setObjectName(_fromUtf8("radioButton_5_6"))
        self.gridLayout_2.addWidget(self.radioButton_5_6, 5, 6, 1, 1)
        self.radioButton_3_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3_4.setText(_fromUtf8(""))
        self.radioButton_3_4.setAutoExclusive(False)
        self.radioButton_3_4.setObjectName(_fromUtf8("radioButton_3_4"))
        self.gridLayout_2.addWidget(self.radioButton_3_4, 3, 4, 1, 1)
        self.radioButton_3_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3_5.setText(_fromUtf8(""))
        self.radioButton_3_5.setAutoExclusive(False)
        self.radioButton_3_5.setObjectName(_fromUtf8("radioButton_3_5"))
        self.gridLayout_2.addWidget(self.radioButton_3_5, 3, 5, 1, 1)
        self.radioButton_3_6 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3_6.setText(_fromUtf8(""))
        self.radioButton_3_6.setAutoExclusive(False)
        self.radioButton_3_6.setObjectName(_fromUtf8("radioButton_3_6"))
        self.gridLayout_2.addWidget(self.radioButton_3_6, 3, 6, 1, 1)
        self.radioButton_4_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4_3.setText(_fromUtf8(""))
        self.radioButton_4_3.setAutoExclusive(False)
        self.radioButton_4_3.setObjectName(_fromUtf8("radioButton_4_3"))
        self.gridLayout_2.addWidget(self.radioButton_4_3, 4, 3, 1, 1)
        self.radioButton_3_7 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3_7.setText(_fromUtf8(""))
        self.radioButton_3_7.setAutoExclusive(False)
        self.radioButton_3_7.setObjectName(_fromUtf8("radioButton_3_7"))
        self.gridLayout_2.addWidget(self.radioButton_3_7, 3, 7, 1, 1)
        self.radioButton_4_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4_4.setText(_fromUtf8(""))
        self.radioButton_4_4.setAutoExclusive(False)
        self.radioButton_4_4.setObjectName(_fromUtf8("radioButton_4_4"))
        self.gridLayout_2.addWidget(self.radioButton_4_4, 4, 4, 1, 1)
        self.radioButton_4_6 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4_6.setText(_fromUtf8(""))
        self.radioButton_4_6.setAutoExclusive(False)
        self.radioButton_4_6.setObjectName(_fromUtf8("radioButton_4_6"))
        self.gridLayout_2.addWidget(self.radioButton_4_6, 4, 6, 1, 1)
        self.radioButton_5_1 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5_1.setText(_fromUtf8(""))
        self.radioButton_5_1.setAutoExclusive(False)
        self.radioButton_5_1.setObjectName(_fromUtf8("radioButton_5_1"))
        self.gridLayout_2.addWidget(self.radioButton_5_1, 5, 1, 1, 1)
        self.radioButton_4_7 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4_7.setText(_fromUtf8(""))
        self.radioButton_4_7.setAutoExclusive(False)
        self.radioButton_4_7.setObjectName(_fromUtf8("radioButton_4_7"))
        self.gridLayout_2.addWidget(self.radioButton_4_7, 4, 7, 1, 1)
        self.radioButton_6_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6_2.setText(_fromUtf8(""))
        self.radioButton_6_2.setAutoExclusive(False)
        self.radioButton_6_2.setObjectName(_fromUtf8("radioButton_6_2"))
        self.gridLayout_2.addWidget(self.radioButton_6_2, 6, 2, 1, 1)
        self.radioButton_5_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5_2.setText(_fromUtf8(""))
        self.radioButton_5_2.setAutoExclusive(False)
        self.radioButton_5_2.setObjectName(_fromUtf8("radioButton_5_2"))
        self.gridLayout_2.addWidget(self.radioButton_5_2, 5, 2, 1, 1)
        self.radioButton_6_7 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6_7.setText(_fromUtf8(""))
        self.radioButton_6_7.setAutoExclusive(False)
        self.radioButton_6_7.setObjectName(_fromUtf8("radioButton_6_7"))
        self.gridLayout_2.addWidget(self.radioButton_6_7, 6, 7, 1, 1)
        self.radioButton_7_7 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_7_7.setText(_fromUtf8(""))
        self.radioButton_7_7.setAutoExclusive(False)
        self.radioButton_7_7.setObjectName(_fromUtf8("radioButton_7_7"))
        self.gridLayout_2.addWidget(self.radioButton_7_7, 7, 7, 1, 1)
        self.radioButton_5_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5_5.setText(_fromUtf8(""))
        self.radioButton_5_5.setAutoExclusive(False)
        self.radioButton_5_5.setObjectName(_fromUtf8("radioButton_5_5"))
        self.gridLayout_2.addWidget(self.radioButton_5_5, 5, 5, 1, 1)
        self.radioButton_6_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6_4.setText(_fromUtf8(""))
        self.radioButton_6_4.setAutoExclusive(False)
        self.radioButton_6_4.setObjectName(_fromUtf8("radioButton_6_4"))
        self.gridLayout_2.addWidget(self.radioButton_6_4, 6, 4, 1, 1)
        self.radioButton_5_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5_3.setText(_fromUtf8(""))
        self.radioButton_5_3.setAutoExclusive(False)
        self.radioButton_5_3.setObjectName(_fromUtf8("radioButton_5_3"))
        self.gridLayout_2.addWidget(self.radioButton_5_3, 5, 3, 1, 1)
        self.radioButton_6_1 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6_1.setText(_fromUtf8(""))
        self.radioButton_6_1.setAutoExclusive(False)
        self.radioButton_6_1.setObjectName(_fromUtf8("radioButton_6_1"))
        self.gridLayout_2.addWidget(self.radioButton_6_1, 6, 1, 1, 1)
        self.radioButton_7_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_7_3.setText(_fromUtf8(""))
        self.radioButton_7_3.setAutoExclusive(False)
        self.radioButton_7_3.setObjectName(_fromUtf8("radioButton_7_3"))
        self.gridLayout_2.addWidget(self.radioButton_7_3, 7, 3, 1, 1)
        self.radioButton_7_1 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_7_1.setText(_fromUtf8(""))
        self.radioButton_7_1.setAutoExclusive(False)
        self.radioButton_7_1.setObjectName(_fromUtf8("radioButton_7_1"))
        self.gridLayout_2.addWidget(self.radioButton_7_1, 7, 1, 1, 1)
        self.radioButton_7_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_7_2.setText(_fromUtf8(""))
        self.radioButton_7_2.setAutoExclusive(False)
        self.radioButton_7_2.setObjectName(_fromUtf8("radioButton_7_2"))
        self.gridLayout_2.addWidget(self.radioButton_7_2, 7, 2, 1, 1)
        self.radioButton_7_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_7_4.setText(_fromUtf8(""))
        self.radioButton_7_4.setAutoExclusive(False)
        self.radioButton_7_4.setObjectName(_fromUtf8("radioButton_7_4"))
        self.gridLayout_2.addWidget(self.radioButton_7_4, 7, 4, 1, 1)
        self.radioButton_7_6 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_7_6.setText(_fromUtf8(""))
        self.radioButton_7_6.setAutoExclusive(False)
        self.radioButton_7_6.setObjectName(_fromUtf8("radioButton_7_6"))
        self.gridLayout_2.addWidget(self.radioButton_7_6, 7, 6, 1, 1)
        self.radioButton_7_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_7_5.setText(_fromUtf8(""))
        self.radioButton_7_5.setAutoExclusive(False)
        self.radioButton_7_5.setObjectName(_fromUtf8("radioButton_7_5"))
        self.gridLayout_2.addWidget(self.radioButton_7_5, 7, 5, 1, 1)
        self.radioButton_0_1 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_0_1.setAutoFillBackground(True)
        self.radioButton_0_1.setStyleSheet(_fromUtf8("gridline-color: rgb(255, 0, 0);"))
        self.radioButton_0_1.setText(_fromUtf8(""))
        self.radioButton_0_1.setAutoExclusive(False)
        self.radioButton_0_1.setObjectName(_fromUtf8("radioButton_0_1"))
        self.gridLayout_2.addWidget(self.radioButton_0_1, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton.setText(_translate("MainWindow", "Push", None))
        self.pushButton_2.setText(_translate("MainWindow", "Back", None))

